<div class="row">
	<?php
		foreach ($this->client_data as $contact) { ?>

			<div class="col-md-6 col-sm-12">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="media">
							<div class="pull-left media-left">
								<img src="<?php echo $this->basePath().'/media/zoop-cx/avatar/'.$contact['Avatar']; ?>" class="img-rounded c-avatar c-avatar-lg">
								<?php $smile = $contact['flag'] == 1 ? 'success' : 'danger' ?>
								<h3 class="smiley">
									<span class="label label-<?php echo $smile ?>">
										<?php $smile = $contact['flag'] == 1 ? 'smile' : 'frown' ?>
										<i class="fa fa-<?php echo $smile ?>-o"></i>
									</span>
								</h3>
							</div>
							<div class="media-body">
								<h3 class="media-heading">
									<?php echo $contact['Client Name'] ?>
									<br><small><span class="glyphicon glyphicon-time"></span> 2014-11-12 12:34 am</small>
									<br><small><i class="fa fa-car"></i> <?php echo $contact['Vehicle'] ?></small>
								</h3>
							</div>
						</div>
					</div>
					<div class="panel-body">
                        <audio  id="mp3Player-<?php echo $contact['id'] ?>" class="" >
                            <source src="<?php echo $this->basePath()."/media/zoop-cx/audio/".$contact['Audio'] ?>" type="audio/mpeg">
                            Your browser does not support audio playback. Please <a href="<?php echo $this->basePath()."/media/zoop-cx/audio/".$contact['Audio'] ?>">Download Audio</a>
                        </audio>
						<div class="btn-group tabs btn-group-justified">
							<a	class="btn btn-lg btn-midas play-mp3" 
								id="playAudio-<?php echo $contact['id'] ?>"
								data-target="<?php echo $contact['id'] ?>"
							/>
								<i class="fa fa-volume-down"></i>
								<span id="playLabel-<?php echo $contact['id'] ?>"> Play</span>
							</a>
							<a class="btn btn-lg btn-midas toggle-text tab-control"
								data-target="#complaint-<?php echo $contact['id'] ?>"
								data-enable="#call-<?php echo $contact['id'] ?>"
								data-tab="#commentAction-<?php echo $contact['id'] ?>"
							/> 
								<i class="fa fa-comments-o"></i>
								<span>More</span>
							</a>
							<a id="call-<?php echo $contact['id'] ?>"
								class="btn btn-lg btn-call btn-midas btn-disabled disabled <?php echo $contact['flag'] == 1 ? 'hidden' : ''; ?> tab-control"
								href="tel:0019465856680" data-enable="#resolve-<?php echo $contact['id'] ?>"
								data-target="#resolveAction-<?php echo $contact['id']?>"
								data-tab="#resolveAction-<?php echo $contact['id'] ?>"
							/>
								<i class="fa fa-phone"></i> Call
							</a>
						</div>
						<hr>
						<div class="resolve-action tab-panel slideup" id="resolveAction-<?php echo $contact['id']?>">
						  	<h4>What did you do to resolve this?</h4>
							  	<a class="btn btn-midas c-tooltip" data-toggle="tooltip" title="Offered refund" data-placement="bottom">
							  		<img src="<?php echo $this->basePath().'/media/zoop-cx/icons/action_refund.png' ?>">
							  	</a>
							  	<a class="btn btn-midas c-tooltip" data-toggle="tooltip" title="Offered discount" data-placement="bottom">
							  		<img src="<?php echo $this->basePath().'/media/zoop-cx/icons/action_discount.png' ?>">
							  	</a>
							  	<a class="btn btn-midas c-tooltip" data-toggle="tooltip" title="Replaced parts" data-placement="bottom">
							  		<img src="<?php echo $this->basePath().'/media/zoop-cx/icons/action_replace.png' ?>">
							  	</a>
							  	<a class="btn btn-midas c-tooltip" data-toggle="tooltip" title="Gave explanation" data-placement="bottom">
							  		<img src="<?php echo $this->basePath().'/media/zoop-cx/icons/action_explain.png' ?>">
							  	</a>
						 </div>	
						<div class="comment-action tab-panel" id="commentAction-<?php echo $contact['id']?>">
							<h4>Comment</h4>
							<blockquote>
								<p class="c-complaint-text c-complaint-text-truncate" id="complaint-<?php echo $contact['id'] ?>">
									<?php echo $contact['Complaint Details'] ?>
								</p>
							</blockquote>
						</div>
					</div>
				</div>
			</div>

	<?php
		}
	?>
</div>




