
<div class="row">
	<?php
		foreach ($this->client_data as $contact) { ?>
			<audio  id="mp3Player-<?php echo $contact['id'] ?>" class="" >
				<source src="<?php echo $this->basePath()."/media/zoop-cx/audio/".$contact['Audio'] ?>" type="audio/mpeg">
				<a href="<?php echo $this->basePath()."/media/zoop-cx/audio/".$contact['Audio'] ?>">Play</a>
			</audio>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="media">
							<div class="pull-left media-left">
								<img src="<?php echo $this->basePath().'/media/zoop-cx/avatar/'.$contact['Avatar']; ?>" class="img-rounded c-avatar c-avatar-lg">
								<h3 class="smiley"><span class="label label-info">
									<?php $smile = $contact['flag'] == 1 ? 'smile' : 'frown' ?>
									<i class="fa fa-<?php echo $smile ?>-o"></i>
								</span></h3>
							</div>
							<div class="media-body">
								<div class="media-heading">
									<h4 class="hidden"><?php echo $contact['Status'] == 1 ? '<span class="label label-success">Closed</span>' : '<span class="label label-warning">Open</span> ' ; ?></h4>
									<h4>
										<br>
										<?php echo $contact['Client Name'] ?>
										<br><small><span class="glyphicon glyphicon-time"></span> 2014-11-12 12:34 am</small>
										<br><small><i class="fa fa-car"></i> <?php echo $contact['Vehicle'] ?></small>
									</h4>
								</div>
							</div>
						</div>
					</div>
					<div class="panel-body">
						<div class="btn-group">
							<button class="btn btn-lg col-md-4 btn-midas play-mp3" id="playAudio-<?php echo $contact['id'] ?>" data-target="<?php echo $contact['id'] ?>">
								<span class="fa fa-volume-up"></span> <span id="playLabel-<?php echo $contact['id'] ?>"> Play</span>
							</button>
							<button class="btn btn-lg col-md-4 btn-midas toggle-text" data-target="#complaint-<?php echo $contact['id'] ?>" data-enable="#call-<?php echo $contact['id'] ?>"> 
								More
							</button>
							<button id="call-<?php echo $contact['id'] ?>" class="btn btn-lg col-md-4 btn-midas disabled">
								<i class="fa fa-phone"></i> Call
							</button>
						</div>
						<hr>
						<blockquote>
							<p class="c-complaint-text c-complaint-text-truncate" id="complaint-<?php echo $contact['id'] ?>">
								<?php echo $contact['Complaint Details'] ?>
							</p>
						</blockquote>
						
					</div>
				</div>
			</div>

	<?php
		}
	?>
</div>




