<div class="page-header">
	<div class="container">
		<h1 class="page-title">
			<i class="fa fa-dashboard"></i> 
			<span class="hidden-xs">4Dx Dashboard </span>
			<span class="shop-label">Midas Phoenix </span>
			<small>39 East Southern Avenue</small>
		</h1>
	</div>
</div>
<div class="container">
	<div class="row dashboard-top">
		<div class="col-md-6">
			<h2 class="date-bar">
				Thursday 
				
				<small> <i class="fa fa-calendar"></i>  November 27, 2014 </small>
			</h2>
		</div>
		
	</div>

	<div class="row">
		<div class="col-md-6">
			<?php echo $this->partGoals; ?>
		</div>
		<div class="col-md-6">
			<?php echo $this->partMeetings; ?>
		</div>
	</div>
</div>
-- i will chack, share  and talk five times per day. by Next monday.
-- last meeting
-- last meeting