<div class="page-header">
	<div class="container"><h1 class="page-title"><i class="fa fa-dashboard"></i> Dashboard</h1></div>
</div>
<div class="container">
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row shop-card">
					<div class="media col-sm-12">
						<div class="pull-left">
							<img src="<?php echo $this->basePath().'/media/zoop-cx/shop/1.png'; ?>"  class="img-rounded c-shop img-responsive">
						</div>
						<div class="media-body">
							<h3 class="media-heading">
								Midas Phoenix<br>
								<small><i class="fa fa-building-o"></i>
								39 East Southern Avenue<br>
								Phoenix, AZ 85040
								</small>
							</h3>
							
						</div>
						
					</div>
				</div>
				<div class="row">
					<div class="col-sm-6">
						<?php echo $this->partScore; ?>
					</div>
					<div class="col-sm-6">
						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>