<div class="page-header">
	<div class="container"><h1 class="page-title"><i class="fa fa-dashboard"></i> Dashboard </h1></div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h2 class="date-bar">
				<i class="fa fa-chevron-left"></i>
					<i class="fa fa-calendar"></i> Thursday <small> November 27, 2014 </small>
				<i class="fa fa-chevron-right disabled"></i>
			</h2>
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="row">
						<div class="shop-card col-sm-12">
							<div class="media">
								<div class="pull-left media-left">
									<img src="<?php echo $this->basePath().'/media/zoop-cx/shop/1.png'; ?>"  class="img-rounded c-shop">
								</div>
								<div class="media-body">
									<h3 class="media-heading">
										Midas Phoenix<br>
										<small class="hidden"><i class="fa fa-building-o"></i>
										39 East Southern Avenue<br>
										Phoenix, AZ 85040
										</small>
									</h3>
									<?php echo $this->partNotification; ?>
								</div>
							</div>					
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6">
							<?php echo $this->partScore; ?>
						</div>
						<div class="col-sm-6">
							<?php echo $this->partRating; ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>