<div class="panel panel-midas panel-goal">
	<div class="panel-heading">
		<span>Wildly Important Goal</span>
	</div>
	<div class="panel-body">
		<blockquote id="wig"class="goal">
			I will <span class="goal_text">check, share, and talk five times </span> by <span class="goal_date">Monday, December 1, 2014</span>
		</blockquote>
		<h4>Days Left: 2</h4> 
	</div>
	<div class="panel-footer">
		<div class="btn-group btn-group-justified">
			<a id="completeGoal" class="btn btn-midas btn-lg"> <i class="fa fa-check"></i> Complete</a>
			<a class="btn btn-midas btn-lg"> <i class="fa fa-flag"></i> Set Goals</a>
		</div>
	</div>
</div>
