<div class="notification-container container-fluid">
	<strong>Customer Notification</strong>
	<div class="notification-label">
		<a class="label label-success" href="<?php echo $this->url('cx/notification-interface',array('action' => 'green-flag')) ?>">1 <i class="fa fa-smile-o"></i></a>
		<a class="label label-danger" href="<?php echo $this->url('cx/notification-interface',array('action' => 'red-flag')) ?>">1 <i class="fa fa-frown-o"></i></a>
	</div>
</div>
