<div class="container-fluid notification-container">
		<strong>Notifications: </strong>
		<span class="notification-label">
			<a class="label label-success" href="<?php echo $this->url('cx/notification-interface',array('action' => 'green-flag')) ?>">1 <i class="fa fa-smile-o"></i></a>
			<a class="label label-danger" href="<?php echo $this->url('cx/notification-interface',array('action' => 'red-flag')) ?>">1 <i class="fa fa-frown-o"></i></a>
		</span>
</div>
