
	<div class="scorecard">
		<h3>Sales<small> <a>Details</a></small></h4></h3>
			<div class="c-score c-score-md c-score-justified">
				<div class="row">
					<div class="col-sm-6">
						<small>Today </small><br>
						<i class="fa fa-dollar"></i> 340.0 
					</div>
					<div class="col-sm-6">
						<small>Yesterday </small><br>
						<i class="fa fa-dollar"></i> 449.0 
					</div>
				</div>
			</div>
		<h4>Goal <small><a>Details</a></small></h4>
		<div class="c-score c-score-md c-score-justified">
			<div class="row">
				<div class="col-sm-12">
					<small>Month <i class="fa fa-dollar"></i> 7890 </small> <br>
					<small>Target <i class="fa fa-dollar"></i> 8300 </small> <br>
					 <small>Completion</small>95%
				</div>
			</div>
			<div class="progress midas-progress">
				<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 95%"></div>
			</div>
		</div>
	</div>

