
	<div class="scorecard">
		<h3>Total Sales</h3>
			<div class="c-score c-score-lg c-score-justified">
				<i class="fa fa-dollar"></i> 2190.0
			</div>
		<h4>GOAL</h4>
		<div class="c-score c-score-md c-score-justified">
			<small>Target:</small> <i class="fa fa-dollar"></i> 2300.0 
			<br>
			<small>Completion: </small> 95%
			<div class="progress midas-progress">
				<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 95%"></div>
			</div>
		</div>
	</div>

