
	<div class="scorecard">
		<h3>Total Sales<small><a> Details</a></small></h4></h3>
			<div class="c-score c-score-md c-score-justified">
				<i class="fa fa-dollar"></i> 340.0 <small>Today </small>
				<br>
				<i class="fa fa-dollar"></i> 449.0 <small>Yesterday </small>
				<br>
				<i class="fa fa-dollar"></i> 7890.0 <small>This Month </small>
			</div>
		<h4>Goal <small><a>Details</a></small></h4>
		<div class="c-score c-score-md c-score-justified">
			<i class="fa fa-dollar"></i> 8300.0 <small>Target</small> 
			<br>
			 95% <small>Completion</small>
			<div class="progress midas-progress">
				<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 95%"></div>
			</div>
		</div>
	</div>

