<div class="jumbotron">
	<h1>Cx Launchpad</h1>
</div>
<div>
	<h5 class="red-alert">* This is only a redirect page. Not part of the projected platform.</h5>
</div>
<table class="table">
	<tr>
		<th>
			<a href="<?php echo $this->url('cx/notification-interface',array('action' => 'red-flag')) ?>">Donelly Issue</a>
		</th>
		<td>Midas client Bob Jones is not happy and called Donelly to complain. </td>
	</tr>
	<tr>
		<th>
			<a href="<?php echo $this->url('cx/notification-interface',array('action' => 'green-flag')) ?>">Positive phone survey</a>
		</th>
		<td>Midas client Tiffany is quite happy and made testimonial.</td>
	</tr>
</table>