<style type="text/css">
	.c-main-panel
	{
		min-height: 200px;
	}
</style>
<div class="page-header">
	<div class="media">
		<span class="pull-left media-left">

		</span>
		<div class="media-body">
			<h3 class="media-heading">Complaint Report #230AC <span class="label label-warning">OPEN</span>
			<br>
			 <i><small>Opened at 2014-11-17 11:10</small></i></h3>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<div class="btn-group">
			<button class="btn btn-default">Start</button>
			<button class="btn btn-default">Close</button>
		</div>

		<div class="btn-group">
			<button class="btn btn-default">Bookmark</button>
			<button class="btn btn-default">Share</button>
		</div>
	</div>
	<hr>
</div>
<div class="row">
	<div class="col-sm-4">
		<h4>Customer Profile</h4>
		<div class="panel panel-default c-main-panel">
			<div class="panel-body">
				<img src="<?php echo $this->basePath().'/media/zoop-cx/avatar/avatar-1.jpg'; ?>" class="img-thumbnail c-avatar">
			</div>
			<table class="table table-striped">
				<tr>
					<td>
						<span class="glyphicon glyphicon-user"></span>

					</td>
					<td>Bob Jones</td>
				</tr>
				<tr>
					<td>
						<span class="glyphicon glyphicon-earphone"></span>
					</td>
					<td><span class="c-tel">63 9465856680</span></td>
				</tr>
				<tr>
					<td>
						<i class="fa fa-car"></i>
					</td>
					<td>Blue Cheverolet Corvette Coupe</td>
				</tr>
				<tr>
					<td>
						<span class="glyphicon glyphicon-home"></span>
					</td>
					<td>
						<address>
							1 Main Street, Tain, Highland IV20 1YW, UK
						</address>
					</td>
				</tr>
			</table>
		</div>
	</div>
	<div class="col-sm-8">
		<h4>Details</h4>
		<div class="panel panel-default c-main-panel">
			<table class="table table-striped">
				<tr>
					<th>Audio</th>
					<td>
						<audio controls>
						  <source src="<?php echo $this->basePath()."/media/sample_audio.mp3" ?>" type="audio/mpeg">
						  <a href="<?php echo $this->basePath()."/media/sample_audio.mp3" ?>">Play</a>
						</audio>
					</td>
				</tr>
				<tr>
					<th>Text Body</th>
					<td>
						<span class="ticket-body">I am a very dissatisfied customer, and will not give out any recommendations for the Midas location on Mutual Way in Appleton.  Here is what I experienced on 11/6/14.

Brought in our vehicle at 4:00 p.m for an appointment which we had for out Expedition to get warranty brake pad work.  We were told ½ hour to 1 hour time for this service job.  When we got to the counter the person behind the counter seemed to be under the influence of some sort of drug or alcohol, he was talking slow, slurring and did not even look at us.  He (Mike) also had his entire family in some back room and was going back there off and on to deal with them, wife and kids it appeared to be.  The kids were yelling and screaming, not sure how you run this business but this is the last thing I would want to hear when waiting for a vehicle.  We were told that it would take an hour, left the building at 4:18 and came back at 5:20 and I was told it was almost done.  Then 45 minutes later I was told they were having problems getting a wheel back on – seriously???  
</span>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-4">
		<h4>History</h4>
		<div class="panel panel-default c-main-panel">
			<div class="panel-body">
			<div class="media">
					<div class="pull-left">

					</div>
					<div class="media-body">
						<h5 class="media-heading"><strong>Status Change</strong> <small>2014-10-11 12:04:01</small></h5>
						Opened
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-sm-8">
		<h4>Comments</h4>
		<div class="panel panel-default c-main-panel">
			<div class="panel-body">
				<div class="media">
					<div class="pull-left">

					</div>
					<div class="media-body">
						<h5 class="media-heading"><strong>Jim Armstrong</strong> <small>2014-10-11 12:04:01</small></h5>
						Will contact him. 
					</div>
				</div>
			<hr>
			<button class="btn btn-default btn-xs">Add Comment</button>
		</div>
	</div>
</div>