<?php echo $this->doctype(); ?>
<style type="text/css">
    .c-notif-counter {
        font-size: 11pt;
        font-weight: bold;
    }
</style>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Cx'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/c-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/notification.js')
            ->prependFile($this->basePath() . '/js/jquery.jmp3.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-midas navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('cx/notification-interface') ?>"><img src="<?php echo $this->basePath() . '/img/brand.png' ?>" class="c-brand" ?></a>
                    <p class="navbar-text hidden">
                        <span class="fa fa-frown-o"></span>
                        <a href="<?php echo $this->url('cx/notification-interface',array('action' => 'red-flag')); ?>">
                            <span class="label label-danger c-notif-counter">1</span>
                        </a>
                        <span class="fa fa-smile-o"></span>
                         <a href="<?php echo $this->url('cx/notification-interface',array('action' => 'green-flag')); ?>">
                            <span class="label label-success c-notif-counter">1</span>
                        </a>
                    </p>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav hidden">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                <div class="navbar-right">
                    
                </div>
                </div><!--/.nav-collapse -->

            </div>
        </nav>
        <div class="container-fluids">
            <?php echo $this->content; ?>
            <hr>
        </div>
        <div class="container">
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by ZOOP. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
